doctrine:
    dbal:
        connections:
            default:
                driver: pdo_mysql
                host: "%env(DATABASE_HOST)%"
                port: "%env(DATABASE_PORT)%"
                dbname: "%env(DATABASE_NAME)%"
                user: "%env(DATABASE_USER)%"
                password: "%env(DATABASE_PASSWORD)%"
                charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
