version: '3.8'
services:
    php:
        build:
            context: "./docker/php"
            dockerfile: "Dockerfile"
        container_name: php
        restart: always
        volumes:
            - ./project:/usr/src/app
        depends_on:
            - db

    nginx:
        container_name: nginx
        image: nginx:1.17.5-alpine
        restart: always
        volumes:
            - ./project/public/:/usr/src/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        depends_on:
            - php
  
    db:
        container_name: db
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task_manager
            MYSQL_USER: task_manager_user
            MYSQL_PASSWORD: 123456
        volumes:
            - ./docker/db:/var/lib/mysql
        ports:
            - 6042:3306