version: '3.8'
services:
    php:
        build: ./docker/php/
        container_name: php
        restart: always
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
            - rabbitmq

    nginx:
        container_name: nginx
        image: nginx:1.17.5-alpine
        restart: always
        volumes:
            - ./public/:/usr/src/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - ${NGINX_EXPOSE_PORT}:80
        depends_on:
            - php
  
    db:
        container_name: db
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./docker/db:/var/lib/mysql
        ports:
            - ${DATABASE_EXPOSE_PORT}:3306
    
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.8-management
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
            
volumes:
    db: