version: '3.8'
services:
    php:
        build: ./docker/php/
        container_name: php
        restart: always
        volumes:
            - ./project:/usr/src/app
        environment:
            - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages
        depends_on:
            - db
            - rabbitmq

    nginx:
        container_name: nginx
        image: nginx:1.17.5-alpine
        restart: always
        volumes:
            - ./project/public/:/usr/src/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80
        depends_on:
            - php
  
    db:
        container_name: db
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task_manager
            MYSQL_USER: task_manager_user
            MYSQL_PASSWORD: 123456
        volumes:
            - ./docker/db:/var/lib/mysql
        ports:
            - 6042:3306
    
    rabbitmq:
        container_name: rabbitmq
        build: ./docker/rabbitmq/
        restart: always
        volumes:
            - rabbitmq:/var/lib/rabbitmq/
        ports:
            - "5672:5672"
            - "15672:15672"
            
volumes:
    rabbitmq:
    db: