framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async: 'amqp://guest:guest@rabbitmq:5672/%2f'
             sync: 'sync://'
            # failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
             'App\Message\TaskCreateMessage': sync
             'App\Message\TaskChangeStatusMessage': sync
             'App\Message\TaskAssignMessage': sync
