security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
#            lazy: ~
            guard:
                entry_point: App\Security\TokenAuthenticator
                authenticators:
                    - App\Security\TokenAuthenticator
#    access_control:
#        - { path: ^/api/v2/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/create_code, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/lndngpgsmth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_USER }